// ./src/app/layout.tsx

// Removed the import for `next/font` due to conflict with custom Babel configuration.
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Directly applying the class for font-family until a better resolution is found.
  // Consider using a global CSS rule to apply the font to your body or specific classes.
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
